---
 layout: page
 title: Schur polynomials
 permalink: /Schur_polynomials
---Let $\Lambda=\{\mu = (\mu_1,\dots, \mu_n)\in\mathbb Z^n \mid \mu_1\geq \cdots\geq \mu_n \geq 0\} \subseteq \mathbb Z^n_{\geq 0}$. For each $\mu \in \Lambda$, define $\nabla_\mu \in \mathbb Z[x_1,\dots, x_n]^\text{sign}$ to be the [antisymmetric](https://defsmath.github.io/DefsMath/invariant_polynomials_under_group_action) [polynomial](https://defsmath.github.io/DefsMath/polynomial_ring) under the [sign representation](https://defsmath.github.io/DefsMath/sign_representation) of the [symmetric group](https://defsmath.github.io/DefsMath/symmetric_group) given by $$\nabla_\mu = \sum_{s\in S_n} \text{sign}(s) x^{s(\mu)} = \det\left|\begin{matrix}x_1^{\mu_1}  & x_1^{\mu_2} & \cdots & x_1^{\mu_n} \\ x_2^{\mu_1} & x_2^{\mu_2} & \cdots & x_2^{\mu_n} \\ \vdots &\vdots & \ddots &\vdots \\ x_n^{\mu_1} & x_n^{\mu_2}&\cdots & x_n^{\mu_n}\end{matrix} \right|.$$ The second equality follows from the [Leibniz formula](https://defsmath.github.io/DefsMath/Leibniz_formula) for [determinants](https://defsmath.github.io/DefsMath/determinant). 

Set $\rho \in \Lambda$ to $\rho = (n-1,n-2,\dots, 1, 0)$. Up to sign, $\nabla_\rho$ is the [Vandermonde determinant](https://defsmath.github.io/DefsMath/Vandermonde_determinant). 

Because $\mathbb Z[x_1,\dots, x_n]^\text{sign}$ [is](https://defsmath.github.io/DefsMath/antisymmetric_polynomials_have_a_Vandermonde_factor) a [rank](https://defsmath.github.io/DefsMath/rank_of_a_module)-one [free](https://defsmath.github.io/DefsMath/free_module) [module](https://defsmath.github.io/DefsMath/module_over_a_ring) over $\mathbb Z[x_1,\dots, x_n]^{S_n}$ with [generator](https://defsmath.github.io/DefsMath/generate_an_R-module) $\Delta_n$, it follows that $\nabla_\rho$ is also a [generator](https://defsmath.github.io/DefsMath/#####################generator) of this [module](https://defsmath.github.io/DefsMath/###################module). Thus for every $\mu\in \Lambda$ there exists a unique [polynomial](https://defsmath.github.io/DefsMath/################polynomial) $s_\mu\in\mathbb Z[x_1,\dots, x_n]^{S_n}$ called the **Schur polynomial** of $\mu$ such that $\nabla_{\mu + \rho} = s_\mu \cdot\nabla_\rho$. 

Explicitly, $s_\mu = \nabla_{\mu + \rho}/\nabla_\rho$. 