---
 layout: page
 title: tensor product of vector spaces
 permalink: /tensor_product_of_vector_spaces
---Given two [vector spaces](https://defsmath.github.io/DefsMath/definitions/vector_space) $V_1$ and $V_2$, $V_1 \otimes V_2$ is called the **tensor product** of $V_1$ and $V_2$ and it is defined as follows: 

Let $F(V_1 \times V_2)$ be the [free vector space](https://defsmath.github.io/DefsMath/free_vector_space) generated by $V_1 \times V_2$, and let $K \subset F(V_1 \times V_2)$ be the [subspace](https://defsmath.github.io/DefsMath/subspace) of $F(V_1 \times V_2)$ generated by the elements 
$$\begin{align*} &(v_1 + v_1', v_2) - (v_1,v_2) - (v_1', v_2)\\ &(v_1, v_2+v_2') - (v_1,v_2)- (v_1, v_2') \\ &(\lambda v_1, v_2) - \lambda (v_1, v_2) \\ &(v_1, \lambda v_2) - \lambda(v_1,v_2)\end{align*}$$ for all $v_1,v_1'\in V_1$, $v_2, v_2' \in V_2$, and $\lambda \in \mathbb R$. The **tensor product** $V_1 \otimes V_2$ is the [quotient vector space](https://defsmath.github.io/DefsMath/quotient_vector_space) $$V_1 \otimes V_2 = F(V_1 \times V_2)/K.$$

Wikidata ID: [Q3406761
https://www.wikidata.org/wiki/Q1163016](https://www.wikidata.org/wiki/Q3406761
https://www.wikidata.org/wiki/Q1163016)